version: '3.7'

services:
  localstack:
    image: localstack/localstack-full
    container_name: localstack
    healthcheck:
      test: "nc -vz localstack 4566"
      interval: 2s
      timeout: 30s
      retries: 15
    ports:
      - 4566-4593:4566-4593
      - 8080:8080
    environment:
      - SERVICES=sqs,ses
      - PORT_WEB_UI=8080
      - DEBUG=0
      - DATA_DIR=./tmp/localstack/data
      - LAMBDA_EXECUTOR=local
      - KINESIS_ERROR_PROBABILITY=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOSTNAME=localstack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack-entrypoint.sh:/docker-entrypoint-initaws.d/localstack-entrypoint.sh
      - ./templates/:/docker-entrypoint-initaws.d/templates/
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    depends_on:
      - "localstack"
    ports:
      - 5432:5432
    healthcheck:
      test: "nc -vz localhost 5432"
      interval: 2s
      timeout: 30s
      retries: 15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
